// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5c3HJUnwbrz4_hOm5zF8VaTsB-oI4DEo',
    appId: '1:470215885665:web:d3c7befe9cdbe42f12fb20',
    messagingSenderId: '470215885665',
    projectId: 'depi-d52e8',
    authDomain: 'depi-d52e8.firebaseapp.com',
    storageBucket: 'depi-d52e8.firebasestorage.app',
    measurementId: 'G-Y8LSLWPMKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOKyeqMW1MR-hLpSaY0aJFEJQUINXDV5Q',
    appId: '1:470215885665:android:7ee876a6d996c1fe12fb20',
    messagingSenderId: '470215885665',
    projectId: 'depi-d52e8',
    storageBucket: 'depi-d52e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm_pwH9g0IgaXSb9D0-w3Clu4OJpyY_lc',
    appId: '1:470215885665:ios:48fdc19d34ab8deb12fb20',
    messagingSenderId: '470215885665',
    projectId: 'depi-d52e8',
    storageBucket: 'depi-d52e8.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm_pwH9g0IgaXSb9D0-w3Clu4OJpyY_lc',
    appId: '1:470215885665:ios:48fdc19d34ab8deb12fb20',
    messagingSenderId: '470215885665',
    projectId: 'depi-d52e8',
    storageBucket: 'depi-d52e8.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5c3HJUnwbrz4_hOm5zF8VaTsB-oI4DEo',
    appId: '1:470215885665:web:62f3289b0b5b7b6712fb20',
    messagingSenderId: '470215885665',
    projectId: 'depi-d52e8',
    authDomain: 'depi-d52e8.firebaseapp.com',
    storageBucket: 'depi-d52e8.firebasestorage.app',
    measurementId: 'G-FQBNC3165D',
  );
}
